[general]
import = [
        "~/.config/alacritty/base16-dark.toml",
        "~/.config/alacritty/keybindings.toml",
        "alacritty-theme/themes/gruvbox_dark.toml",
        ]
working_directory = "None"
live_config_reload = true
ipc_socket = true

[window]
decorations = "Full"
opacity = 0.7
dynamic_title = true
decorations_theme_variant = "Dark"

[font]
normal = { family ="FiraCode Nerd Font Mono", style= "Regular" }
bold = { family ="FiraCode Nerd Font Mono", style= "Bold" }
italic = { family ="FiraCode Nerd Font Mono", style= "Italic" }
bold_italic = { family ="FiraCode Nerd Font Mono", style= "Bold Italic" }
size = 12

[colors]
# Monokai Primary
primary.background = "#2D2A2E"
primary.foreground = "#FCFCFA"
# Monokai Normal
normal.black = "#403E41"
normal.red = "#FF6188"
normal.green = "#A9DC76"
normal.yellow = "#FFD866"
normal.blue = "#FC9867"
normal.magenta = "#AB9DF2"
normal.cyan = "#78DCE8"
normal.white = "#FCFCFA"
# Monokai Bright
bright.black = "#727072"
bright.red = "#FF6188"
bright.green = "#A9DC76"
bright.yellow = "#FFD866"
bright.blue = "#FC9867"
bright.magenta = "#AB9DF2"
bright.cyan = "#78DCE8"
bright.white = "#FCFCFA"
